// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ustktljkkajcmpsmtmrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzdGt0bGpra2FqY21wc210bXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDU1NDcsImV4cCI6MjA2MDMyMTU0N30.YfI8dOR7DAjJP_o282Cx6ePZF75wuThMKRlZQhjqF_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);